services:

  bestellservice:
    build:
      context: ./bestellservice
      dockerfile: Dockerfile
    image: ghcr.io/le-rudolph/cloud-pizzasystem/bestellen
    environment:
      - QUEUE_URI=amqp://guest:guest@q:5672
      - DATABASE_URI=mongodb://root:example@mongo
      # Products
      - "PRODUCTS_URL=http://produktservice:3000/pizza"
    ports:
      - "127.0.0.1:14621:14621"

  produktservice:
    build:
      context: ./produktservice
      dockerfile: Dockerfile
    image: ghcr.io/le-rudolph/cloud-pizzasystem/produktservice
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASS=example

  lieferantenservice:
    build:
      context: ./lieferantenservice
      dockerfile: Dockerfile
    image: ghcr.io/le-rudolph/cloud-pizzasystem/lieferantenservice
    environment:
      # queue setup
      - QUEUE_HOST=q
      - QUEUE_NAME=order
      - QUEUE_USER=guest
      - QUEUE_PASS=guest
      # MongoDB credentials
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASS=example


  mongo:
    image: mongo:7.0.11
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  q:
    image: rabbitmq:3.13
    ports:
      - "127.0.0.1:5672:5672"
