apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: q
  name: q
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: q
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: q
    spec:
      containers:
        - image: rabbitmq:3.13
          name: q
          ports:
            - containerPort: 5672
          resources: {}
      restartPolicy: Always
status: {}
