services:
  lieferantenservice:
    build:
      context: .
      dockerfile: Dockerfile
  queue:
    image: rabbitmq:3.13
    container_name: pizza-queue
  mongo:
    image: mongo
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
