services:
  lieferantenservice:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - QUEUE_HOST=pizza-queue
      - QUEUE_NAME=order
      - QUEUE_USER=guest
      - QUEUE_PASS=guest
      # - PYTHONUNBUFFERED=1
  pizza-queue:
    image: rabbitmq:3.13
    # expose:
    #   - 5672
    ports:
      - "5672:5672"
  mongo:
    image: mongo
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
