services:
  produktservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASS=example
  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
      