services:
  produktservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
      